const dares = [
    "Sing a song for the group!",
    "Do 10 push-ups.",
    "Talk in a funny accent for the next 5 minutes.",
    "Send a selfie doing a funny face.",
    "Let someone text anything they want from your phone.",
    "Eat a spoonful of a condiment you don't like.",
    "Do a handstand against the wall for 30 seconds.",
    "Call a friend and sing 'Happy Birthday' to them, even if it's not their birthday.",
    "Attempt to breakdance for 1 minute.",
    "Pretend to be a robot until your next turn.",
    "Let the group choose a new hairstyle for you.",
    "Read the last text message you received out loud.",
    "Do your best impression of a celebrity.",
    "Recite a poem in the most dramatic tone possible.",
    "Go outside and yell 'I love [random object]!' as loud as you can.",
    "Do a plank for one minute without stopping.",
    "Speak only in rhymes for the next three rounds.",
    "Wear your clothes inside out for the remainder of the game.",
    "Text your crush a random emoji without any context.",
  "Change your social media profile picture to a funny image for 1 hour.",
  "Send a random GIF to 5 people you don't know well.",
  "Post a silly selfie on social media with a ridiculous caption.",
  "Tweet a random emoji 10 times in a row.",
  "Change your WhatsApp status to 'I love pineapples' for 1 hour.",
  "Send a voice message saying 'I'm a chicken' to a friend.",
  "Post a funny story on your social media timeline.",
  "Do a live video on Instagram singing a silly song.",
  "Send a random meme to 3 people.",
  "Change your phone wallpaper to a funny image for 1 day.",
  "Call a friend and pretend to be a robot.",
  "Post a photo of your shoes on social media with a funny caption.",
  "Send a 'typing...' screenshot to a friend.",
  "Do a funny dance in front of a webcam.",
  "Change your social media bio to something ridiculous for 1 hour.",
  "Send a random joke to 5 people.",
  "Post a 'guess the song' challenge on social media.",
  "Do a lip-sync video of a funny song.",
  "Send a funny sticker to 10 people on WhatsApp.",
  "Change your Instagram theme to a funny one for 1 day.",
  "Post a 'day in my life' vlog on social media.",
  "Send a random funny GIF to your crush.",
  "Do a funny voiceover on a random video.",
  "Change your Twitter username to something silly for 1 hour.",
  "Post a funny 'would you rather' question on social media.",
  "Send a 'good morning' message with a silly image.",
  "Do a funny review of a random product online.",
  "Change your Facebook profile picture to a funny animation.",
  "Send a random funny quote to 5 people.",
  "Post a silly question on Quora.",
  "Do a funny unboxing video of a random product.",
  "Change your WhatsApp display name to something funny for 1 hour.",
  "Send a funny meme to your boss (if you have a good relationship).",
  "Post a funny 'this or that' challenge on social media.",
  "Do a funny tutorial on how to do something silly.",
  "Change your social media theme to a funny one for 1 day.",
  "Send a random funny image to 3 people.",
  "Post a funny 'guess the emoji' challenge on social media.",
  "Do a funny voiceover on a random meme.",
  "Change your Instagram username to something silly for 1 hour.",
  "Send a funny joke to 10 people on WhatsApp.",
  "Post a silly poem on social media.",
  "Do a funny reaction video to a random video.",
  "Change your Twitter profile picture to a funny image for 1 hour.",
  "Send a random funny video to 5 people.",
  "Post a funny 'fill in the blank' challenge on social media.",
  "Do a funny Q&A session on social media.",
  "Change your WhatsApp status to something ridiculous for 1 hour.",
  "Send a funny GIF to your friend's group chat.",
  "Post a silly drawing on social media.",
  "Do a funny 'try not to laugh' challenge video.",
  "Change your social media bio to something funny for 1 day.",
  "Send a random funny image to your crush.",
  "Post a funny 'challenge accepted' post on social media.",
  "Do a funny review of a random restaurant online.",
  "Change your phone ringtone to a funny sound for 1 day.",
  "Send a funny sticker to 5 people on WhatsApp.",
  "Post a silly 'what I think vs what I do' meme on social media.",
  "Do a funny 'day in the life' video on social media.",
  "Change your Instagram bio to something ridiculous for 1 hour.",
  "Send a funny meme to 3 people you don't know well.",
  "Post a funny 'top 5' list on social media.",
  "Do a funny voiceover on a random TikTok video.",
  "Change your WhatsApp display name to something silly for 1 day.",
  "Send a funny joke to your friend's group chat.",
  "Post a silly 'procrastination' meme on social media.",
  "Do a funny 'haul' video on social media.",
  "Change your social media theme to a funny one for 1 hour.",
  "Send a random funny GIF to 5 people.",
  "Post a funny 'relationship goals' meme on social media.",
  "Do a funny 'reaction' video to a random meme.",
  "Change your Twitter bio to something ridiculous for 1 hour.",
  "Send a funny image to 10 people on WhatsApp.",
  "Post a silly 'adulting' meme on social media.",
  "Do a funny tutorial on how to do something silly online.",
  "Change your Instagram username to something funny for 1 day.",
  "Send a funny voice message to a friend.",
  "Post a funny 'fandom' meme on social media.",
  "Do a funny 'guess the song' challenge on social media.",
  "Change your WhatsApp status to something funny for 1 day.",
  "Send a funny sticker to 3 people on WhatsApp.",
  "Post a silly 'pet' photo on social media.",
  "Do a funny 'review' of a random product online.",
  "Change your social media profile picture to a funny image for 1 day.",
  "Send a random funny meme to 5 people.",
  "Post a funny 'quote' on social media.",
  "Do a funny 'Q&A' session on social media.",
  "Change your Twitter profile picture to a funny image for 1 hour.",
  "Send a funny GIF to your crush.",
  "Post a silly 'challenge' on social media.",
  "Do a funny 'reaction' video to a random video.",
  "Change your Instagram bio to something funny for 1 day.",
  "Send a funny joke to 5 people on WhatsApp.",
  "Post a funny 'meme' on social media.",
  "Do a funny 'voiceover' on a random video.",
  "Change your WhatsApp display name to something silly for 1 hour.",
  "Send a funny image to 3 people you don't know well.",
  "Post a silly 'question' on social media.",
  "Do a funny 'tutorial' on how to do something silly online.",
  "Change your social media theme to a funny one for 1 day.",
  "Send a random funny GIF to 10 people.",
  "Post a funny 'story' on social media.",
  "Do a funny 'review' of a random restaurant online.",
  "Change your Twitter username to something funny for 1 hour.",
  "Send a funny sticker to 5 people on WhatsApp.",
  "Post a silly 'meme' on social media.",
  "Do a funny 'Q&A' session on social media.",
  "Change your Instagram username to something silly for 1 day.",
  "Send a funny voice message to a friend.",
  "Post a funny 'challenge' on social media.",
  "Do a funny 'reaction' video to a random meme.",
  "Change your WhatsApp status to something funny for 1 hour.",
  "Send a funny GIF to 3 people on WhatsApp.",
  "Post a silly 'photo' on social media.",
  "Do a funny 'tutorial' on how to do something silly online.",
  "Change your social media profile picture to a funny image for 1 hour.",
    "Balance a spoon on your nose for 30 seconds."
];
module.exports = {
    command: 'dare',
    description: 'picks random dare',
    category: 'fun',
    execute: async (sock, m, {
        args,
        text,
        q,
        quoted,
        mime,
        qmsg,
        isMedia,
        groupMetadata,
        groupName,
        participants,
        groupOwner,
        groupAdmins,
        isBotAdmins,
        isAdmins,
        isGroupOwner,
        isCreator,
        prefix,
        reply,
        config
    }) => {
    const randomDare = dares[Math.floor(Math.random() * dares.length)];
    await reply(`🔥 𝕕𝕒𝕣𝕖: ${randomDare}`);
}
    };
    
