const facts = [
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
  "There's a species of jellyfish that's immortal.",
  "The Eiffel Tower can be 15 cm taller in summer due to thermal expansion.",
  "You can't tickle yourself.",
  "The world's largest living organism is a fungus.",
  "There's a type of sea slug that can photosynthesize.",
  "The longest word in English has 45 letters.",
  "You lose about 4kg of skin cells every year.",
  "There's a tribe in Africa that has no concept of 'no'.",
  "The world's deepest lake is over 1,700 meters deep.",
  "Humans share 60% of their DNA with bananas.",
  "The first computer virus was created in 1983.",
  "The world's largest snowflake was 38 cm wide.",
  "You can get sunburned through glass.",
  "The shortest IQ test has only 3 questions.",
  "There's a species of shark that has a 3-year gestation period.",
  "The world's largest mammal can't jump.",
  "You blink about 12-15 times per minute.",
  "The world's smallest mammal is the bumblebee bat.",
  "The longest recorded flight of a chicken is 13 seconds.",
  "The world's largest diamond was found in 1905.",
  "You have a second brain in your gut.",
  "The world's driest desert is not the Sahara.",
  "There's a lake in Africa that's so alkaline it can turn animals into statues.",
  "The world's largest insect is the stick insect.",
  "You can see the Earth's curvature from space.",
  "The world's smallest country is Vatican City.",
  "There's a species of snake that can go without eating for a year.",
  "The world's largest wave was 24 meters high.",
  "You have about 100,000 hairs on your head.",
  "The world's fastest land animal can run 100 meters in under 10 seconds.",
  "There's a type of mushroom that's carnivorous.",
  "The world's largest city has over 38 million people.",
  "You can get a tan from LED lights.",
  "The world's smallest bird is the bee hummingbird.",
  "The world's largest animal eats tiny plankton.",
  "There's a species of lizard that can run on water.",
  "The world's driest place is Atacama Desert.",
  "You use about 200 muscles to take a step.",
  "The world's largest painting is over 2,000 square meters.",
  "There's a type of jellyfish that's 90% water.",
  "The world's largest gold coin weighs 10 kg.",
  "You can hear your own voice differently than others.",
  "The world's smallest guitar is 10 micrometers long.",
  "There's a species of frog that can freeze and thaw.",
  "The world's largest library has over 170 million items.",
  "You have about 60,000 miles of blood vessels.",
  "The world's smallest bone is in your ear.",
  "There's a type of ant that can lift 5,000 times its weight.",
  "The world's largest maze is over 1,000 hectares.",
  "You can see the Andromeda galaxy with the naked eye.",
  "The world's smallest computer is 1mm cube.",
  "There's a species of shark that lives in freshwater.",
  "The world's largest spider is the Goliath Birdeater.",
  "You can get brain freeze from eating cold food too fast.",
  "The world's smallest reptile is the dwarf gecko.",
  "There's a type of bacteria that can survive in space.",
  "The world's largest fish is the whale shark.",
  "You blink about 1 billion times in a lifetime.",
  "The world's smallest flower is the watermeal.",
  "There's a species of octopus with venom that's lethal to humans.",
  "The world's largest tree is over 2,000 years old.",
  "You can see your own nose in your peripheral vision.",
  "The world's smallest mammal by weight is the Etruscan shrew.",
  "There's a type of star that's diamond.",
  "The world's largest cave is over 600 km long.",
  "You can get motion sickness from reading in a car.",
  "The world's smallest country by population is Vatican City.",
  "There's a species of jellyfish that's been to space.",
  "The world's largest island is Greenland.",
  "You have a unique nose print.",
  "The world's smallest book is 0.5 mm x 0.5 mm.",
  "There's a type of lizard that can shoot blood from its eyes.",
  "The world's largest animal migration is the Great Migration.",
  "You can hear your own heartbeat in a quiet room.",
  "The world's smallest guitar string is 1/100th the width of a human hair.",
  "There's a species of shark that has 300 rows of teeth.",
  "The world's largest volcano is under the sea.",
  "You can get a sore throat from talking too much.",
  "The world's smallest ant is 0.5 mm long.",
  "There's a type of mushroom that's fluorescent.",
  "The world's largest desert is the Antarctic Desert.",
  "You can see the Moon's shadow during a solar eclipse.",
  "The world's smallest snake is the threadsnake.",
  "There's a species of lizard that's venomous.",
  "The world's largest fish market is in Japan.",
  "You can get wrinkles from sleeping on your side.",
  "The world's smallest mammal by length is the Kittiwake's mouse-eared bat.",
  "There's a type of bacteria that eats metal.",
  "The world's largest mountain range is under the ocean.",
  "You can hear sounds in your head without external noise.",
  "The world's smallest computer chip is 0.3 mm x 0.3 mm.",
  "There's a species of frog that's transparent.",
  "The world's largest amphibian is the Chinese giant salamander.",
  "You can get a tan in winter.",
  "The world's smallest book page is 0.1 mm x 0.1 mm.",
  "There's a type of jellyfish that's 2 meters wide.",
  "The world's largest coral reef is the Great Barrier Reef."
]
module.exports = {
    command: 'fact',
    description: 'picks random sap fact',
    category: 'fun',
    execute: async (sock, m, {
        args,
        text,
        q,
        quoted,
        mime,
        qmsg,
        isMedia,
        groupMetadata,
        groupName,
        participants,
        groupOwner,
        groupAdmins,
        isBotAdmins,
        isAdmins,
        isGroupOwner,
        isCreator,
        prefix,
        reply,
        config
    }) => {
    const randomFact = facts[Math.floor(Math.random() * facts.length)];
    await reply(`🔥 𝕤𝕒𝕡 𝕗𝕒𝕔𝕥: ${randomFact}`);
}
    };
    
