const truths = [
"What's your biggest fear?",
    "What was your most embarrassing moment?",
    "If you could be invisible for a day, what would you do?",
    "Who was your first crush?",
    "What’s one thing you’ve never told anyone?",
    "Have you ever cheated on a test?",
    "What's the most trouble you've ever gotten into?",
    "What's your biggest regret?",
    "Have you ever lied to get out of plans?",
    "What's the weirdest thing you've ever eaten?",
    "Have you ever pretended to like a gift you hated?",
    "What's the most childish thing you still do?",
    "Have you ever had a secret nickname for someone?",
    "What's the biggest lie you've told your parents?",
    "Have you ever snooped through someone else's things?",
    "What's the most embarrassing thing in your search history?",
    "Have you ever cried during a movie? Which one?",
    "What's something you're secretly proud of?",
    "Have you ever kept a secret you shouldn't have?",
    "What's the worst date you've ever been on?",
    "Have you ever pretended to be sick to avoid something?",
    "What's the most ridiculous rumor you've heard about yourself?",
    "Have you ever broken something and blamed someone else?",
    "What's your guilty pleasure song?",
    "Have you ever had a crush on a friend's partner?",
    "What's the most impulsive thing you've ever done?",
    "Have you ever stolen anything?",
    "What's something you're embarrassed to admit you like?",
    "Have you ever ghosted someone? Why?",
    "What's your biggest insecurity?",
    "Have you ever lied about your age?",
    "What's the strangest dream you've ever had?",
    "Have you ever pretended to know someone you didn't?",
    "What's the most expensive thing you've broken?",
    "Have you ever re-gifted a present?",
    "What's something you'd never do in front of others?",
    "Have you ever had a paranormal experience?",
    "What's your most irrational fear?",
    "Have you ever faked being good at something?",
    "What's the most childish argument you've had?",
    "Have you ever kept a diary? Did anyone read it?",
    "What's your biggest pet peeve?",
    "Have you ever had a crush on a teacher/boss?",
    "What's the worst advice you've ever given?",
    "Kiss, marry, kill with three celebrities",
    "What's the strangest habit you have?",
    "Have you ever pretended to laugh at a joke you didn't get?",
    "What's something you're secretly competitive about?",
    "Have you ever walked in on someone accidentally?",
  "What's the most embarrassing thing you've done in public?",
  "Have you ever lied to get out of a situation?",
  "What's your biggest fear?",
  "What's one thing you're proud of accomplishing?",
  "Have you ever had a crush on someone in this room?",
  "What's the most childish thing you still do?",
  "What's a secret you've never told anyone?",
  "Have you ever broken something and blamed someone else?",
  "What's the most awkward date you've been on?",
  "What's one thing you wish you could change about yourself?",
  "Have you ever had a fight with a friend? What was it about?",
  "What's the most embarrassing song you listen to?",
  "Have you ever pretended to be someone you're not?",
  "What's something you're not good at but pretend to be?",
  "Have you ever fallen asleep in class or at work?",
  "What's the most embarrassing thing in your phone?",
  "Have you ever sent a text to the wrong person?",
  "What's something you've done that you regret?",
  "Have you ever eaten something weird?",
  "What's the most adventurous thing you've done?",
  "Have you ever had a ghostly experience?",
  "What's your biggest pet peeve?",
  "Have you ever been caught doing something you shouldn't?",
  "What's the most embarrassing thing you've worn?",
  "Have you ever had a crush on a teacher?",
  "What's something you're ashamed of?",
  "Have you ever lied on a resume?",
  "What's the most embarrassing thing you've done for love?",
  "Have you ever been caught lying?",
  "What's something you used to believe in as a kid?",
  "Have you ever had a nickname? What was it?",
  "What's the most embarrassing thing about your family?",
  "Have you ever been in a weird group photo?",
  "What's something you've done that was totally out of character?",
  "Have you ever had a strange dream that's stuck with you?",
  "What's the most embarrassing thing you've said in front of people?",
  "Have you ever been embarrassed by someone close to you?",
  "What's something you're secretly good at?",
  "Have you ever had a bad habit that you can't break?",
  "What's the most embarrassing thing you've done online?",
  "Have you ever been caught talking about someone behind their back?",
  "What's something you've done that you got away with?",
  "Have you ever had a funny encounter with a stranger?",
  "What's the most embarrassing thing you've done at school?",
  "Have you ever had a crush on someone much older or younger?",
  "What's something you're glad you didn't do?",
  "Have you ever been in a situation where you didn't know what to do?",
  "What's the most embarrassing thing about your appearance?",
  "Have you ever had a weird phobia?",
  "What's something you've done that you thought was cool at the time?",
  "Have you ever been caught cheating on a test?",
  "What's the most embarrassing thing you've done in front of a crush?",
  "Have you ever had a strange superstition?",
  "What's something you're really bad at?",
  "Have you ever been part of a group decision you didn't agree with?",
  "What's the most embarrassing thing you've done at work?",
  "Have you ever had a secret talent?",
  "What's something you've done that you're not proud of?",
  "Have you ever been caught in a lie about your age?",
  "What's the most embarrassing thing you've done while drunk?",
  "Have you ever had a weird obsession?",
  "What's something you've done that you keep as a secret?",
  "Have you ever been in a situation where you felt totally out of place?",
  "What's the most embarrassing thing you've done in a public place?",
  "Have you ever had a crush on a fictional character?",
  "What's something you're really embarrassed about?",
  "Have you ever done something you thought was right but turned out wrong?",
  "What's the most embarrassing thing you've done to get attention?",
  "Have you ever had a strange habit?",
  "What's something you've done that you wish you could take back?",
  "Have you ever been caught doing something silly?",
  "What's the most embarrassing thing you've done at a party?",
  "Have you ever had a weird dream about someone you know?",
  "What's something you're glad you did?",
  "Have you ever been part of a prank gone wrong?",
  "What's the most embarrassing thing you've done online?",
  "Have you ever had a crush on someone you shouldn't?",
  "What's something you've done that's really funny in hindsight?",
  "Have you ever been in a situation where you had to improvise?",
  "What's the most embarrassing thing you've done in front of friends?",
  "Have you ever had a strange feeling about something that came true?",
  "What's something you've done that was really brave?",
  "Have you ever been caught in a embarrassing lie?",
  "What's the most embarrassing thing you've done at a restaurant?",
  "Have you ever had a weird encounter with a celebrity?",
  "What's something you've done that's really cool?",
  "Have you ever been part of a group that's been caught doing something?",
  "What's the most embarrassing thing you've done while singing?",
  "Have you ever had a crush on a friend's sibling?",
  "What's something you've done that's really silly?",
  "Have you ever been in a situation where you had to think fast?",
  "What's the most embarrassing thing you've done at a family gathering?",
  "Have you ever had a weird food combination?",
  "What's something you've done that's really embarrassing but funny now?",
  "Have you ever been caught watching something you shouldn't?",
  "What's the most embarrassing thing you've done in a car?",
  "Have you ever had a strange conversation with someone?",
  "What's something you've done that's really unique?",
  "Have you ever been part of a weird tradition?",
  "What's the most embarrassing thing you've done in front of a large group?",
  "Have you ever had a weird smell issue?",
  "What's something you've done that's really adventurous?",
  "Have you ever been caught in a awkward situation?",
  "What's the most embarrassing thing you've done at a store?",
  "Have you ever had a weird encounter with an animal?",
  "What's something you've done that's really spontaneous?",
  "Have you ever been part of a group that's done something embarrassing?",
  "What's the most embarrassing thing you've done while traveling?",
  "Have you ever had a crush on someone from a different culture?",
  "What's something you've done that's really funny?",
  "Have you ever been in a situation where you had to laugh to avoid crying?",
  "What's the most embarrassing thing you've done at a concert?",
  "Have you ever had a weird dream about a friend?",
  "What's something you've done that's really creative?",
  "Have you ever been caught doing something you shouldn't on your phone?",
  "What's the most embarrassing thing you've done at a wedding?",
  "Have you ever had a strange feeling about someone?",
  "What's something you've done that's really bold?",
  "Have you ever been part of a group that's been in an awkward situation?",
    "What's the most embarrassing text you've sent to the wrong person?"
];

 module.exports = {
    command: 'truth',
    description: 'picks random truth',
    category: 'fun',
    execute: async (sock, m, {
        args,
        text,
        q,
        quoted,
        mime,
        qmsg,
        isMedia,
        groupMetadata,
        groupName,
        participants,
        groupOwner,
        groupAdmins,
        isBotAdmins,
        isAdmins,
        isGroupOwner,
        isCreator,
        prefix,
        reply,
        config
    }) => {
    const randomtruth = truths[Math.floor(Math.random() * truths.length)];
    await reply(`🔥𝕥𝕣𝕦𝕥𝕙: ${randomtruth}`);
}
    };